# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_files/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 605)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.fuel_map_grid_scroll_area = QtWidgets.QScrollArea(self.central_widget)
        self.fuel_map_grid_scroll_area.setGeometry(QtCore.QRect(10, 50, 581, 511))
        self.fuel_map_grid_scroll_area.setWidgetResizable(True)
        self.fuel_map_grid_scroll_area.setObjectName("fuel_map_grid_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.fuel_map_grid_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.progress_bar = QtWidgets.QProgressBar(self.central_widget)
        self.progress_bar.setGeometry(QtCore.QRect(10, 560, 951, 21))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.tab_widget = QtWidgets.QTabWidget(self.central_widget)
        self.tab_widget.setGeometry(QtCore.QRect(600, 0, 360, 560))
        self.tab_widget.setIconSize(QtCore.QSize(15, 15))
        self.tab_widget.setObjectName("tab_widget")
        self.simulation_settings_tab = QtWidgets.QWidget()
        self.simulation_settings_tab.setObjectName("simulation_settings_tab")
        self.scroll_area = QtWidgets.QScrollArea(self.simulation_settings_tab)
        self.scroll_area.setGeometry(QtCore.QRect(0, 0, 360, 530))
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.simulation_settings_widget = QtWidgets.QWidget()
        self.simulation_settings_widget.setGeometry(QtCore.QRect(0, 0, 358, 528))
        self.simulation_settings_widget.setObjectName("simulation_settings_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.simulation_settings_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 311, 348))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.vertical_layout.setObjectName("vertical_layout")
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.vertical_layout.addWidget(self.line_10)
        self.sim_settings_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sim_settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_settings_label.setObjectName("sim_settings_label")
        self.vertical_layout.addWidget(self.sim_settings_label)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.vertical_layout.addWidget(self.line_4)
        self.sim_settings_form_layout = QtWidgets.QFormLayout()
        self.sim_settings_form_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.sim_settings_form_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.sim_settings_form_layout.setContentsMargins(10, 5, 10, 5)
        self.sim_settings_form_layout.setVerticalSpacing(10)
        self.sim_settings_form_layout.setObjectName("sim_settings_form_layout")
        self.num_sim_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_sim_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_sim_label.setObjectName("num_sim_label")
        self.sim_settings_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.num_sim_label)
        self.num_sim_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.num_sim_line_edit.setObjectName("num_sim_line_edit")
        self.sim_settings_form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.num_sim_line_edit)
        self.sim_duration_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sim_duration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_duration_label.setObjectName("sim_duration_label")
        self.sim_settings_form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sim_duration_label)
        self.sim_duration_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sim_duration_line_edit.setObjectName("sim_duration_line_edit")
        self.sim_settings_form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sim_duration_line_edit)
        self.vertical_layout.addLayout(self.sim_settings_form_layout)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.vertical_layout.addWidget(self.line_3)
        self.wind_settings_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wind_settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_settings_label.setObjectName("wind_settings_label")
        self.vertical_layout.addWidget(self.wind_settings_label)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.vertical_layout.addWidget(self.line_6)
        self.wind_form_layout = QtWidgets.QFormLayout()
        self.wind_form_layout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.wind_form_layout.setContentsMargins(10, 5, 10, 5)
        self.wind_form_layout.setHorizontalSpacing(60)
        self.wind_form_layout.setVerticalSpacing(10)
        self.wind_form_layout.setObjectName("wind_form_layout")
        self.wind_speed_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wind_speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_speed_label.setObjectName("wind_speed_label")
        self.wind_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.wind_speed_label)
        self.wind_speed_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.wind_speed_line_edit.setObjectName("wind_speed_line_edit")
        self.wind_form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wind_speed_line_edit)
        self.wind_direction_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wind_direction_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_direction_label.setObjectName("wind_direction_label")
        self.wind_form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.wind_direction_label)
        self.wind_direction_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.wind_direction_line_edit.setObjectName("wind_direction_line_edit")
        self.wind_form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.wind_direction_line_edit)
        self.vertical_layout.addLayout(self.wind_form_layout)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vertical_layout.addWidget(self.line)
        self.init_conditions_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.init_conditions_label.setAlignment(QtCore.Qt.AlignCenter)
        self.init_conditions_label.setObjectName("init_conditions_label")
        self.vertical_layout.addWidget(self.init_conditions_label)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.vertical_layout.addWidget(self.line_5)
        self.form_layout_3 = QtWidgets.QFormLayout()
        self.form_layout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.form_layout_3.setContentsMargins(10, 5, 10, 5)
        self.form_layout_3.setHorizontalSpacing(60)
        self.form_layout_3.setVerticalSpacing(10)
        self.form_layout_3.setObjectName("form_layout_3")
        self.initialFireIntensity_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.initialFireIntensity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.initialFireIntensity_label.setObjectName("initialFireIntensity_label")
        self.form_layout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.initialFireIntensity_label)
        self.initialFireIntensityLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.initialFireIntensityLineEdit.setObjectName("initialFireIntensityLineEdit")
        self.form_layout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.initialFireIntensityLineEdit)
        self.ingnitionStartTime_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ingnitionStartTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ingnitionStartTime_label.setObjectName("ingnitionStartTime_label")
        self.form_layout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ingnitionStartTime_label)
        self.ignitionStartTime_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ignitionStartTime_line_edit.setObjectName("ignitionStartTime_line_edit")
        self.form_layout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ignitionStartTime_line_edit)
        self.vertical_layout.addLayout(self.form_layout_3)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.vertical_layout.addWidget(self.line_8)
        self.scroll_area.setWidget(self.simulation_settings_widget)
        self.tab_widget.addTab(self.simulation_settings_tab, "")
        self.fuel_type_legend_tab = QtWidgets.QWidget()
        self.fuel_type_legend_tab.setObjectName("fuel_type_legend_tab")
        self.fuel_type_scroll_area = QtWidgets.QScrollArea(self.fuel_type_legend_tab)
        self.fuel_type_scroll_area.setGeometry(QtCore.QRect(0, 0, 360, 530))
        self.fuel_type_scroll_area.setWidgetResizable(True)
        self.fuel_type_scroll_area.setObjectName("fuel_type_scroll_area")
        self.fuel_type_scroll_area_widget_contents = QtWidgets.QWidget()
        self.fuel_type_scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 358, 528))
        self.fuel_type_scroll_area_widget_contents.setObjectName("fuel_type_scroll_area_widget_contents")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.fuel_type_scroll_area_widget_contents)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 0, 321, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.fuel_type_legend_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.fuel_type_legend_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fuel_type_legend_label.setObjectName("fuel_type_legend_label")
        self.verticalLayout_2.addWidget(self.fuel_type_legend_label)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 317, 78))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_type_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.add_type_button.setObjectName("add_type_button")
        self.horizontalLayout.addWidget(self.add_type_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.remove_type_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.remove_type_button.setObjectName("remove_type_button")
        self.horizontalLayout.addWidget(self.remove_type_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_2.addWidget(self.line_9)
        self.modify_fuel_map_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.modify_fuel_map_label.setAlignment(QtCore.Qt.AlignCenter)
        self.modify_fuel_map_label.setObjectName("modify_fuel_map_label")
        self.verticalLayout_2.addWidget(self.modify_fuel_map_label)
        self.line_12 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_2.addWidget(self.line_12)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.x_range_min_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x_range_min_line_edit.setObjectName("x_range_min_line_edit")
        self.gridLayout.addWidget(self.x_range_min_line_edit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.y_range_max_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.y_range_max_line_edit.setPlaceholderText("")
        self.y_range_max_line_edit.setObjectName("y_range_max_line_edit")
        self.gridLayout.addWidget(self.y_range_max_line_edit, 1, 4, 1, 1)
        self.x_range_max_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.x_range_max_line_edit.setObjectName("x_range_max_line_edit")
        self.gridLayout.addWidget(self.x_range_max_line_edit, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.y_range_min_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.y_range_min_line_edit.setObjectName("y_range_min_line_edit")
        self.gridLayout.addWidget(self.y_range_min_line_edit, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.fuel_type_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.fuel_type_combo_box.setObjectName("fuel_type_combo_box")
        self.fuel_type_combo_box.addItem("")
        self.fuel_type_combo_box.addItem("")
        self.horizontalLayout_3.addWidget(self.fuel_type_combo_box)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_13 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_2.addWidget(self.line_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.modify_fuel_map_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.modify_fuel_map_button.setObjectName("modify_fuel_map_button")
        self.horizontalLayout_4.addWidget(self.modify_fuel_map_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_11 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        self.fuel_type_scroll_area.setWidget(self.fuel_type_scroll_area_widget_contents)
        self.tab_widget.addTab(self.fuel_type_legend_tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab_widget.addTab(self.tab_3, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 143, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.current_env_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.current_env_label.setObjectName("current_env_label")
        self.horizontalLayout_2.addWidget(self.current_env_label)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 20))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_export = QtWidgets.QMenu(self.menubar)
        self.menu_export.setObjectName("menu_export")
        self.menu_settings = QtWidgets.QMenu(self.menubar)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_simulation = QtWidgets.QMenu(self.menubar)
        self.menu_simulation.setObjectName("menu_simulation")
        self.menu_import = QtWidgets.QMenu(self.menubar)
        self.menu_import.setObjectName("menu_import")
        MainWindow.setMenuBar(self.menubar)
        self.action_create_environment = QtWidgets.QAction(MainWindow)
        self.action_create_environment.setObjectName("action_create_environment")
        self.action_import_environment = QtWidgets.QAction(MainWindow)
        self.action_import_environment.setObjectName("action_import_environment")
        self.action_Initial_Conditions = QtWidgets.QAction(MainWindow)
        self.action_Initial_Conditions.setObjectName("action_Initial_Conditions")
        self.actionWind = QtWidgets.QAction(MainWindow)
        self.actionWind.setObjectName("actionWind")
        self.actionFuel_Map = QtWidgets.QAction(MainWindow)
        self.actionFuel_Map.setObjectName("actionFuel_Map")
        self.action_export_simulation = QtWidgets.QAction(MainWindow)
        self.action_export_simulation.setObjectName("action_export_simulation")
        self.action_export_summary_file = QtWidgets.QAction(MainWindow)
        self.action_export_summary_file.setObjectName("action_export_summary_file")
        self.action_export_environment = QtWidgets.QAction(MainWindow)
        self.action_export_environment.setObjectName("action_export_environment")
        self.action_import_simulation = QtWidgets.QAction(MainWindow)
        self.action_import_simulation.setObjectName("action_import_simulation")
        self.action_import_summary_file = QtWidgets.QAction(MainWindow)
        self.action_import_summary_file.setObjectName("action_import_summary_file")
        self.actionWorking_Directory = QtWidgets.QAction(MainWindow)
        self.actionWorking_Directory.setObjectName("actionWorking_Directory")
        self.actionOutput_Directory = QtWidgets.QAction(MainWindow)
        self.actionOutput_Directory.setObjectName("actionOutput_Directory")
        self.actionDefault_Simulation_Duration = QtWidgets.QAction(MainWindow)
        self.actionDefault_Simulation_Duration.setObjectName("actionDefault_Simulation_Duration")
        self.actionSimulation_Runs = QtWidgets.QAction(MainWindow)
        self.actionSimulation_Runs.setObjectName("actionSimulation_Runs")
        self.action_select_output_files = QtWidgets.QAction(MainWindow)
        self.action_select_output_files.setObjectName("action_select_output_files")
        self.action_run_sim = QtWidgets.QAction(MainWindow)
        self.action_run_sim.setObjectName("action_run_sim")
        self.action_view_sim = QtWidgets.QAction(MainWindow)
        self.action_view_sim.setObjectName("action_view_sim")
        self.action_user_settings = QtWidgets.QAction(MainWindow)
        self.action_user_settings.setObjectName("action_user_settings")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_import_fuel_map = QtWidgets.QAction(MainWindow)
        self.action_import_fuel_map.setObjectName("action_import_fuel_map")
        self.action_import_dem = QtWidgets.QAction(MainWindow)
        self.action_import_dem.setObjectName("action_import_dem")
        self.action_export_fuel_map = QtWidgets.QAction(MainWindow)
        self.action_export_fuel_map.setObjectName("action_export_fuel_map")
        self.action_export_dem = QtWidgets.QAction(MainWindow)
        self.action_export_dem.setObjectName("action_export_dem")
        self.menu_file.addAction(self.action_create_environment)
        self.menu_export.addAction(self.action_export_environment)
        self.menu_export.addAction(self.action_export_summary_file)
        self.menu_export.addAction(self.action_export_fuel_map)
        self.menu_export.addAction(self.action_export_dem)
        self.menu_settings.addAction(self.action_user_settings)
        self.menu_settings.addAction(self.action_select_output_files)
        self.menu_help.addAction(self.action_about)
        self.menu_simulation.addAction(self.action_run_sim)
        self.menu_simulation.addAction(self.action_view_sim)
        self.menu_import.addAction(self.action_import_environment)
        self.menu_import.addAction(self.action_import_summary_file)
        self.menu_import.addAction(self.action_import_fuel_map)
        self.menu_import.addAction(self.action_import_dem)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_import.menuAction())
        self.menubar.addAction(self.menu_export.menuAction())
        self.menubar.addAction(self.menu_simulation.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        self.fuel_type_combo_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FireScape Rx"))
        self.sim_settings_label.setText(_translate("MainWindow", "Simulation Settings"))
        self.num_sim_label.setText(_translate("MainWindow", "Number of Simulations"))
        self.sim_duration_label.setText(_translate("MainWindow", "Simulation Duration"))
        self.wind_settings_label.setText(_translate("MainWindow", "Wind Settings"))
        self.wind_speed_label.setText(_translate("MainWindow", "Wind Speed"))
        self.wind_direction_label.setText(_translate("MainWindow", "Wind Direction"))
        self.init_conditions_label.setText(_translate("MainWindow", "Initial conditions"))
        self.initialFireIntensity_label.setText(_translate("MainWindow", "Initial Fire Intensity"))
        self.ingnitionStartTime_label.setText(_translate("MainWindow", "Ignition Start Time"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.simulation_settings_tab), _translate("MainWindow", "Simulation Settings"))
        self.fuel_type_legend_label.setText(_translate("MainWindow", "Fuel Type Legend:"))
        self.add_type_button.setText(_translate("MainWindow", "Add Type"))
        self.remove_type_button.setText(_translate("MainWindow", "Remove Type"))
        self.modify_fuel_map_label.setText(_translate("MainWindow", "Modify Fuel Map:"))
        self.label_2.setText(_translate("MainWindow", "Y range:"))
        self.label.setText(_translate("MainWindow", "X range:"))
        self.label_5.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "Fuel Type:"))
        self.fuel_type_combo_box.setCurrentText(_translate("MainWindow", "Untreated"))
        self.fuel_type_combo_box.setItemText(0, _translate("MainWindow", "Untreated"))
        self.fuel_type_combo_box.setItemText(1, _translate("MainWindow", "Treated"))
        self.modify_fuel_map_button.setText(_translate("MainWindow", "Modify"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.fuel_type_legend_tab), _translate("MainWindow", "Fuel Map"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_3), _translate("MainWindow", "Ignition Points"))
        self.current_env_label.setText(_translate("MainWindow", "Current Environment:"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_export.setTitle(_translate("MainWindow", "Export"))
        self.menu_settings.setTitle(_translate("MainWindow", "Settings"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.menu_simulation.setTitle(_translate("MainWindow", "Simulation"))
        self.menu_import.setTitle(_translate("MainWindow", "Import"))
        self.action_create_environment.setText(_translate("MainWindow", "Create Environment"))
        self.action_import_environment.setText(_translate("MainWindow", "Environment"))
        self.action_Initial_Conditions.setText(_translate("MainWindow", "Initial Conditions"))
        self.actionWind.setText(_translate("MainWindow", "Wind"))
        self.actionFuel_Map.setText(_translate("MainWindow", "Fuel Map"))
        self.action_export_simulation.setText(_translate("MainWindow", "Simulation"))
        self.action_export_summary_file.setText(_translate("MainWindow", "Summary File"))
        self.action_export_environment.setText(_translate("MainWindow", "Environment"))
        self.action_import_simulation.setText(_translate("MainWindow", "Simulation"))
        self.action_import_summary_file.setText(_translate("MainWindow", "Summary File"))
        self.actionWorking_Directory.setText(_translate("MainWindow", "Working Directory"))
        self.actionOutput_Directory.setText(_translate("MainWindow", "Output Directory"))
        self.actionDefault_Simulation_Duration.setText(_translate("MainWindow", "Simulation Duration"))
        self.actionSimulation_Runs.setText(_translate("MainWindow", "Simulation Runs"))
        self.action_select_output_files.setText(_translate("MainWindow", "Select Output Files"))
        self.action_run_sim.setText(_translate("MainWindow", "Run"))
        self.action_view_sim.setText(_translate("MainWindow", "View"))
        self.action_user_settings.setText(_translate("MainWindow", "User Settings"))
        self.action_about.setText(_translate("MainWindow", "About"))
        self.action_import_fuel_map.setText(_translate("MainWindow", "Fuel Map"))
        self.action_import_dem.setText(_translate("MainWindow", "Digital Elevation Model"))
        self.action_export_fuel_map.setText(_translate("MainWindow", "Fuel Map"))
        self.action_export_dem.setText(_translate("MainWindow", "Digital Elevation Model"))

